auxiliary build scripts:
* check for used tools in PATH: `jar`, `javac`
* using recursive `cp`
* changed comments and output to stdout

diff --git a/makeBigJar b/makeBigJar
--- a/makeBigJar
+++ b/makeBigJar
@@ -2,36 +2,42 @@
 set -e
 ################################################################################
 #
-#      Author:		Bob Fisch
+#      Author:        Bob Fisch
 #
-#      Description:	
+#      Description:    
 #
 ################################################################################
 #
 #      Revision List
 #
-#      Author						Date		Description
-#      ------						----		-----------
-#      Bob Fisch					2008.10.15  First Issue
-#	   Bob Fisch & Philipp Hübner	2009.07.08  Scripting ameliorations
-#	   Bob Fisch					2010.01.25	Update for new libraries and signature removing
+#      Author                        Date        Description
+#      ------                        ----        -----------
+#      Bob Fisch                     2008.10.15  First Issue
+#      Bob Fisch & Philipp Hübner    2009.07.08  Scripting ameliorations
+#      Bob Fisch                     2010.01.25  Update for new libraries and signature removing
+#      Simon Sobisch                 2017.03.06  Check for jar, use comments instead of `echo`,
+#                                                using recursive cp for libs
 #
 ################################################################################
 
-echo "delete the old archive (if present)"
+# check for jar in PATH
+jar 2>/dev/null 1&>2 || (rc=$? && if test $rc -gt 1; then (echo 'jar not found in $PATH' && exit $rc); fi)
+
+# delete the old archive (if present)
 [ -f structorizer.jar ] && rm structorizer.jar
 
-echo "make directory"
+# make directory
 [ -d jar ] && rm -R jar
 mkdir jar
 
-echo "copy libs"
-cp lib/* jar
+# copy libs
+cp -R lib/* jar
 
-echo "move into jar directory"
-cd jar
+# change into jar directory
+pushd jar
 
-echo "decompress jar's"
+# decompress jar's
+echo "Decompressing jar's ..."
 jar xf bsh-2.0b4.jar
 jar xf swing-layout-1.0.3.jar
 jar xf freehep-graphics2d-2.1.1.jar
@@ -43,24 +49,27 @@ jar xf freehep-xml-2.1.1.jar
 jar xf freehep-graphicsio-svg-2.1.1.jar
 jar xf freehep.jar
 
-echo "deleting signatures"
+# deleting signatures
 rm -f META-INF/*.SF
 rm -f META-INF/*.DSA
 
-echo "remove jar files"
+# remove jar files
 rm *.jar
 
-echo "go back"
-cd ..
+# go back
+popd
 
-echo "copy other files"
+# copy other files
+echo "Copying resources"
 cp -R bin/* jar/
 
-echo "create an new archive"
+# create a new archive
+echo "Create a new archive"
 jar cmf structorizer.big.manifest structorizer.jar -C jar/ .
 
-echo "remove the jar-directory"
+# remove the jar-directory
 rm -R jar/
 
-echo "execute the archive"
+# execute the archive
+echo "Running Structorizer from all-in-one jar"
 java -jar structorizer.jar
diff --git a/makeJar b/makeJar
--- a/makeJar
+++ b/makeJar
@@ -14,14 +14,20 @@ set -e
 #      ------						----		-----------
 #      Bob Fisch					2008.10.04  First Issue
 #	   Bob Fisch & Philipp Hübner	2009.07.08  Scripting ameliorations
+#      Simon Sobisch                2017.03.06  Check for jar
 #
 ################################################################################
+
+# check for jar in PATH
+jar 2>/dev/null 1>&2 || (rc=$? && if test $rc -gt 1; then (echo 'jar not found in $PATH' && exit $rc); fi)
 
 # delete the old archive (if present)
 [ -f structorizer.jar ] && rm structorizer.jar
 
-# create an new archive
+# create a new archive
+echo "Create archive"
 jar cmf structorizer.manifest structorizer.jar -C bin/ .
 
 # execute the archive
+echo "Running Structorizer from jar"
 java -jar structorizer.jar
diff --git a/makeStructorizer b/makeStructorizer
--- a/makeStructorizer
+++ b/makeStructorizer
@@ -16,11 +16,15 @@ set -e
 #      ------						----			-----------
 #      Klaus-Peter Reimers      	2008.06.04      First Issue
 #      Bob Fisch					2006.06.06      Script modified to work within
-#													an Eclipse project	
+#													an Eclipse project
 #	   Bob Fisch & Philipp Hübner	2009.07.08  	Scripting ameliorations
 #      Kay Gürtzig                  2016.12.27      More resource files copied
+#      Simon Sobisch                2017.03.06      Check for javac
 #
 ################################################################################
+
+# check for javac in PATH
+javac -version 2>/dev/null || (rc=$? && echo 'javac not found in $PATH' && exit $rc)
 
 # delete old class files from "lu" package
 echo Removing .class files
@@ -29,16 +33,16 @@ find bin -name '*.class' -exec rm {} \;
 
 # change into the "src" directory
 echo Changing into src directory
-cd src
+pushd src
 
 # compile the generator classes (non-dependant classes)
 echo Compiling non-dependant classes
 javac -d ../bin/ -cp .:../lib/swing-layout-1.0.3.jar:../lib/bsh-2.0b4.jar:../lib/freehep-graphics2d-2.1.1.jar:../lib/freehep-graphicsio-2.1.1.jar:../lib/freehep-io-2.0.2.jar:../lib/freehep-swing-2.0.3.jar:../lib/freehep-util-2.0.2.jar:../lib/freehep.jar:../lib/freehep-xml-2.1.1.jar:../lib/freehep-graphicsio-svg-2.1.1.jar lu/fisch/structorizer/generators/*.java
 
 # compile the application itself (and all dependend classes)
-echo Compiling Structorizer
+echo "Compiling Structorizer"
 javac -d ../bin/ -cp .:../lib/swing-layout-1.0.3.jar:../lib/bsh-2.0b4.jar:../lib/freehep-graphics2d-2.1.1.jar:../lib/freehep-graphicsio-2.1.1.jar:../lib/freehep-io-2.0.2.jar:../lib/freehep-swing-2.0.3.jar:../lib/freehep-util-2.0.2.jar:../lib/freehep.jar:../lib/freehep-xml-2.1.1.jar:../lib/freehep-graphicsio-svg-2.1.1.jar Structorizer.java
-echo Compiling Structorizer Applet
+echo "Compiling Structorizer Applet"
 javac -d ../bin/ -cp .:../lib/swing-layout-1.0.3.jar:../lib/bsh-2.0b4.jar:../lib/freehep-graphics2d-2.1.1.jar:../lib/freehep-graphicsio-2.1.1.jar:../lib/freehep-io-2.0.2.jar:../lib/freehep-swing-2.0.3.jar:../lib/freehep-util-2.0.2.jar:../lib/freehep.jar:../lib/freehep-xml-2.1.1.jar:../lib/freehep-graphicsio-svg-2.1.1.jar StructorizerApplet.java
 
 # copying some other files to binary tree
@@ -58,8 +62,8 @@ echo Changing into binary directory
 cd ../bin/
 
 # run the application
-echo Running Structorizer
+echo "Running Structorizer"
 java -cp .:../lib/swing-layout-1.0.3.jar:../lib/bsh-2.0b4.jar:../lib/freehep-graphics2d-2.1.1.jar:../lib/freehep-graphicsio-2.1.1.jar:../lib/freehep-io-2.0.2.jar:../lib/freehep-swing-2.0.3.jar:../lib/freehep-util-2.0.2.jar:../lib/freehep.jar:../lib/freehep-xml-2.1.1.jar:../lib/freehep-graphicsio-svg-2.1.1.jar Structorizer
 
 # move back into the folder where we started
-cd ..
+popd
